/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedClientPortalRouteImport } from './routes/_authenticated/client-portal'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedOnboardingBusinessIdRouteImport } from './routes/_authenticated/onboarding.$businessId'
import { Route as AuthenticatedCrmBusinessIdRouteImport } from './routes/_authenticated/crm.$businessId'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicHooksTestOnboardingEmailRouteImport } from './routes/api/public/hooks/test-onboarding-email'
import { Route as ApiPublicHooksOnboardingRemindersRouteImport } from './routes/api/public/hooks/onboarding-reminders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientPortalRoute =
  AuthenticatedClientPortalRouteImport.update({
    id: '/client-portal',
    path: '/client-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingBusinessIdRoute =
  AuthenticatedOnboardingBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedCrmBusinessIdRoute =
  AuthenticatedCrmBusinessIdRouteImport.update({
    id: '/crm/$businessId',
    path: '/crm/$businessId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTestOnboardingEmailRoute =
  ApiPublicHooksTestOnboardingEmailRouteImport.update({
    id: '/api/public/hooks/test-onboarding-email',
    path: '/api/public/hooks/test-onboarding-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOnboardingRemindersRoute =
  ApiPublicHooksOnboardingRemindersRouteImport.update({
    id: '/api/public/hooks/onboarding-reminders',
    path: '/api/public/hooks/onboarding-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/client-portal': typeof AuthenticatedClientPortalRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/support': typeof AuthenticatedSupportRoute
  '/users': typeof AuthenticatedUsersRoute
  '/crm/$businessId': typeof AuthenticatedCrmBusinessIdRoute
  '/onboarding/$businessId': typeof AuthenticatedOnboardingBusinessIdRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/api/public/hooks/onboarding-reminders': typeof ApiPublicHooksOnboardingRemindersRoute
  '/api/public/hooks/test-onboarding-email': typeof ApiPublicHooksTestOnboardingEmailRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/client-portal': typeof AuthenticatedClientPortalRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/support': typeof AuthenticatedSupportRoute
  '/users': typeof AuthenticatedUsersRoute
  '/crm/$businessId': typeof AuthenticatedCrmBusinessIdRoute
  '/onboarding/$businessId': typeof AuthenticatedOnboardingBusinessIdRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/api/public/hooks/onboarding-reminders': typeof ApiPublicHooksOnboardingRemindersRoute
  '/api/public/hooks/test-onboarding-email': typeof ApiPublicHooksTestOnboardingEmailRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/client-portal': typeof AuthenticatedClientPortalRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/crm/$businessId': typeof AuthenticatedCrmBusinessIdRoute
  '/_authenticated/onboarding/$businessId': typeof AuthenticatedOnboardingBusinessIdRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/api/public/hooks/onboarding-reminders': typeof ApiPublicHooksOnboardingRemindersRoute
  '/api/public/hooks/test-onboarding-email': typeof ApiPublicHooksTestOnboardingEmailRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/client-portal'
    | '/onboarding'
    | '/support'
    | '/users'
    | '/crm/$businessId'
    | '/onboarding/$businessId'
    | '/crm/'
    | '/api/public/hooks/onboarding-reminders'
    | '/api/public/hooks/test-onboarding-email'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounts'
    | '/client-portal'
    | '/onboarding'
    | '/support'
    | '/users'
    | '/crm/$businessId'
    | '/onboarding/$businessId'
    | '/crm'
    | '/api/public/hooks/onboarding-reminders'
    | '/api/public/hooks/test-onboarding-email'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/client-portal'
    | '/_authenticated/onboarding'
    | '/_authenticated/support'
    | '/_authenticated/users'
    | '/_authenticated/crm/$businessId'
    | '/_authenticated/onboarding/$businessId'
    | '/_authenticated/crm/'
    | '/api/public/hooks/onboarding-reminders'
    | '/api/public/hooks/test-onboarding-email'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksOnboardingRemindersRoute: typeof ApiPublicHooksOnboardingRemindersRoute
  ApiPublicHooksTestOnboardingEmailRoute: typeof ApiPublicHooksTestOnboardingEmailRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-portal': {
      id: '/_authenticated/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof AuthenticatedClientPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/$businessId': {
      id: '/_authenticated/onboarding/$businessId'
      path: '/$businessId'
      fullPath: '/onboarding/$businessId'
      preLoaderRoute: typeof AuthenticatedOnboardingBusinessIdRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/crm/$businessId': {
      id: '/_authenticated/crm/$businessId'
      path: '/crm/$businessId'
      fullPath: '/crm/$businessId'
      preLoaderRoute: typeof AuthenticatedCrmBusinessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-onboarding-email': {
      id: '/api/public/hooks/test-onboarding-email'
      path: '/api/public/hooks/test-onboarding-email'
      fullPath: '/api/public/hooks/test-onboarding-email'
      preLoaderRoute: typeof ApiPublicHooksTestOnboardingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/onboarding-reminders': {
      id: '/api/public/hooks/onboarding-reminders'
      path: '/api/public/hooks/onboarding-reminders'
      fullPath: '/api/public/hooks/onboarding-reminders'
      preLoaderRoute: typeof ApiPublicHooksOnboardingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingBusinessIdRoute: typeof AuthenticatedOnboardingBusinessIdRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingBusinessIdRoute:
      AuthenticatedOnboardingBusinessIdRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedClientPortalRoute: typeof AuthenticatedClientPortalRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedCrmBusinessIdRoute: typeof AuthenticatedCrmBusinessIdRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedClientPortalRoute: AuthenticatedClientPortalRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedCrmBusinessIdRoute: AuthenticatedCrmBusinessIdRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksOnboardingRemindersRoute:
    ApiPublicHooksOnboardingRemindersRoute,
  ApiPublicHooksTestOnboardingEmailRoute:
    ApiPublicHooksTestOnboardingEmailRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
