/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLeaderboardsRouteImport } from './routes/_authenticated/leaderboards'
import { Route as AuthenticatedClientPortalRouteImport } from './routes/_authenticated/client-portal'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/client-documents'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedUsersTrophiRouteImport } from './routes/_authenticated/users.trophi'
import { Route as AuthenticatedUsersClientUsersRouteImport } from './routes/_authenticated/users.client-users'
import { Route as AuthenticatedSettingsPandadocTemplatesRouteImport } from './routes/_authenticated/settings.pandadoc-templates'
import { Route as AuthenticatedOnboardingBusinessIdRouteImport } from './routes/_authenticated/onboarding.$businessId'
import { Route as AuthenticatedCrmBusinessIdRouteImport } from './routes/_authenticated/crm.$businessId'
import { Route as AuthenticatedUsersTrophiIndexRouteImport } from './routes/_authenticated/users.trophi.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksTestOnboardingEmailRouteImport } from './routes/api/public/hooks/test-onboarding-email'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksPandadocRouteImport } from './routes/api/public/hooks/pandadoc'
import { Route as ApiPublicHooksOnboardingRemindersRouteImport } from './routes/api/public/hooks/onboarding-reminders'
import { Route as ApiPublicHooksBackfillContractsRouteImport } from './routes/api/public/hooks/backfill-contracts'
import { Route as AuthenticatedUsersTrophiUserIdRouteImport } from './routes/_authenticated/users.trophi.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardsRoute =
  AuthenticatedLeaderboardsRouteImport.update({
    id: '/leaderboards',
    path: '/leaderboards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientPortalRoute =
  AuthenticatedClientPortalRouteImport.update({
    id: '/client-portal',
    path: '/client-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/client-documents',
    path: '/client-documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersTrophiRoute =
  AuthenticatedUsersTrophiRouteImport.update({
    id: '/trophi',
    path: '/trophi',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedUsersClientUsersRoute =
  AuthenticatedUsersClientUsersRouteImport.update({
    id: '/client-users',
    path: '/client-users',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedSettingsPandadocTemplatesRoute =
  AuthenticatedSettingsPandadocTemplatesRouteImport.update({
    id: '/settings/pandadoc-templates',
    path: '/settings/pandadoc-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingBusinessIdRoute =
  AuthenticatedOnboardingBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedCrmBusinessIdRoute =
  AuthenticatedCrmBusinessIdRouteImport.update({
    id: '/crm/$businessId',
    path: '/crm/$businessId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersTrophiIndexRoute =
  AuthenticatedUsersTrophiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsersTrophiRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTestOnboardingEmailRoute =
  ApiPublicHooksTestOnboardingEmailRouteImport.update({
    id: '/api/public/hooks/test-onboarding-email',
    path: '/api/public/hooks/test-onboarding-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPandadocRoute = ApiPublicHooksPandadocRouteImport.update({
  id: '/api/public/hooks/pandadoc',
  path: '/api/public/hooks/pandadoc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOnboardingRemindersRoute =
  ApiPublicHooksOnboardingRemindersRouteImport.update({
    id: '/api/public/hooks/onboarding-reminders',
    path: '/api/public/hooks/onboarding-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillContractsRoute =
  ApiPublicHooksBackfillContractsRouteImport.update({
    id: '/api/public/hooks/backfill-contracts',
    path: '/api/public/hooks/backfill-contracts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUsersTrophiUserIdRoute =
  AuthenticatedUsersTrophiUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersTrophiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/client-documents': typeof AuthenticatedClientDocumentsRoute
  '/client-portal': typeof AuthenticatedClientPortalRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/crm/$businessId': typeof AuthenticatedCrmBusinessIdRoute
  '/onboarding/$businessId': typeof AuthenticatedOnboardingBusinessIdRoute
  '/settings/pandadoc-templates': typeof AuthenticatedSettingsPandadocTemplatesRoute
  '/users/client-users': typeof AuthenticatedUsersClientUsersRoute
  '/users/trophi': typeof AuthenticatedUsersTrophiRouteWithChildren
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/users/trophi/$userId': typeof AuthenticatedUsersTrophiUserIdRoute
  '/api/public/hooks/backfill-contracts': typeof ApiPublicHooksBackfillContractsRoute
  '/api/public/hooks/onboarding-reminders': typeof ApiPublicHooksOnboardingRemindersRoute
  '/api/public/hooks/pandadoc': typeof ApiPublicHooksPandadocRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/test-onboarding-email': typeof ApiPublicHooksTestOnboardingEmailRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/users/trophi/': typeof AuthenticatedUsersTrophiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/client-documents': typeof AuthenticatedClientDocumentsRoute
  '/client-portal': typeof AuthenticatedClientPortalRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/crm/$businessId': typeof AuthenticatedCrmBusinessIdRoute
  '/onboarding/$businessId': typeof AuthenticatedOnboardingBusinessIdRoute
  '/settings/pandadoc-templates': typeof AuthenticatedSettingsPandadocTemplatesRoute
  '/users/client-users': typeof AuthenticatedUsersClientUsersRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/trophi/$userId': typeof AuthenticatedUsersTrophiUserIdRoute
  '/api/public/hooks/backfill-contracts': typeof ApiPublicHooksBackfillContractsRoute
  '/api/public/hooks/onboarding-reminders': typeof ApiPublicHooksOnboardingRemindersRoute
  '/api/public/hooks/pandadoc': typeof ApiPublicHooksPandadocRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/test-onboarding-email': typeof ApiPublicHooksTestOnboardingEmailRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/users/trophi': typeof AuthenticatedUsersTrophiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/client-documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/client-portal': typeof AuthenticatedClientPortalRoute
  '/_authenticated/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/crm/$businessId': typeof AuthenticatedCrmBusinessIdRoute
  '/_authenticated/onboarding/$businessId': typeof AuthenticatedOnboardingBusinessIdRoute
  '/_authenticated/settings/pandadoc-templates': typeof AuthenticatedSettingsPandadocTemplatesRoute
  '/_authenticated/users/client-users': typeof AuthenticatedUsersClientUsersRoute
  '/_authenticated/users/trophi': typeof AuthenticatedUsersTrophiRouteWithChildren
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/users/trophi/$userId': typeof AuthenticatedUsersTrophiUserIdRoute
  '/api/public/hooks/backfill-contracts': typeof ApiPublicHooksBackfillContractsRoute
  '/api/public/hooks/onboarding-reminders': typeof ApiPublicHooksOnboardingRemindersRoute
  '/api/public/hooks/pandadoc': typeof ApiPublicHooksPandadocRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/test-onboarding-email': typeof ApiPublicHooksTestOnboardingEmailRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/users/trophi/': typeof AuthenticatedUsersTrophiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/accounts'
    | '/audit'
    | '/client-documents'
    | '/client-portal'
    | '/leaderboards'
    | '/onboarding'
    | '/reports'
    | '/support'
    | '/users'
    | '/crm/$businessId'
    | '/onboarding/$businessId'
    | '/settings/pandadoc-templates'
    | '/users/client-users'
    | '/users/trophi'
    | '/crm/'
    | '/onboarding/'
    | '/users/'
    | '/users/trophi/$userId'
    | '/api/public/hooks/backfill-contracts'
    | '/api/public/hooks/onboarding-reminders'
    | '/api/public/hooks/pandadoc'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/test-onboarding-email'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/users/trophi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/accounts'
    | '/audit'
    | '/client-documents'
    | '/client-portal'
    | '/leaderboards'
    | '/reports'
    | '/support'
    | '/crm/$businessId'
    | '/onboarding/$businessId'
    | '/settings/pandadoc-templates'
    | '/users/client-users'
    | '/crm'
    | '/onboarding'
    | '/users'
    | '/users/trophi/$userId'
    | '/api/public/hooks/backfill-contracts'
    | '/api/public/hooks/onboarding-reminders'
    | '/api/public/hooks/pandadoc'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/test-onboarding-email'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/users/trophi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/audit'
    | '/_authenticated/client-documents'
    | '/_authenticated/client-portal'
    | '/_authenticated/leaderboards'
    | '/_authenticated/onboarding'
    | '/_authenticated/reports'
    | '/_authenticated/support'
    | '/_authenticated/users'
    | '/_authenticated/crm/$businessId'
    | '/_authenticated/onboarding/$businessId'
    | '/_authenticated/settings/pandadoc-templates'
    | '/_authenticated/users/client-users'
    | '/_authenticated/users/trophi'
    | '/_authenticated/crm/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/users/'
    | '/_authenticated/users/trophi/$userId'
    | '/api/public/hooks/backfill-contracts'
    | '/api/public/hooks/onboarding-reminders'
    | '/api/public/hooks/pandadoc'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/test-onboarding-email'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/users/trophi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  ApiPublicHooksBackfillContractsRoute: typeof ApiPublicHooksBackfillContractsRoute
  ApiPublicHooksOnboardingRemindersRoute: typeof ApiPublicHooksOnboardingRemindersRoute
  ApiPublicHooksPandadocRoute: typeof ApiPublicHooksPandadocRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
  ApiPublicHooksTestOnboardingEmailRoute: typeof ApiPublicHooksTestOnboardingEmailRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboards': {
      id: '/_authenticated/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof AuthenticatedLeaderboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-portal': {
      id: '/_authenticated/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof AuthenticatedClientPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-documents': {
      id: '/_authenticated/client-documents'
      path: '/client-documents'
      fullPath: '/client-documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/trophi': {
      id: '/_authenticated/users/trophi'
      path: '/trophi'
      fullPath: '/users/trophi'
      preLoaderRoute: typeof AuthenticatedUsersTrophiRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/users/client-users': {
      id: '/_authenticated/users/client-users'
      path: '/client-users'
      fullPath: '/users/client-users'
      preLoaderRoute: typeof AuthenticatedUsersClientUsersRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/settings/pandadoc-templates': {
      id: '/_authenticated/settings/pandadoc-templates'
      path: '/settings/pandadoc-templates'
      fullPath: '/settings/pandadoc-templates'
      preLoaderRoute: typeof AuthenticatedSettingsPandadocTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/$businessId': {
      id: '/_authenticated/onboarding/$businessId'
      path: '/$businessId'
      fullPath: '/onboarding/$businessId'
      preLoaderRoute: typeof AuthenticatedOnboardingBusinessIdRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/crm/$businessId': {
      id: '/_authenticated/crm/$businessId'
      path: '/crm/$businessId'
      fullPath: '/crm/$businessId'
      preLoaderRoute: typeof AuthenticatedCrmBusinessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/trophi/': {
      id: '/_authenticated/users/trophi/'
      path: '/'
      fullPath: '/users/trophi/'
      preLoaderRoute: typeof AuthenticatedUsersTrophiIndexRouteImport
      parentRoute: typeof AuthenticatedUsersTrophiRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-onboarding-email': {
      id: '/api/public/hooks/test-onboarding-email'
      path: '/api/public/hooks/test-onboarding-email'
      fullPath: '/api/public/hooks/test-onboarding-email'
      preLoaderRoute: typeof ApiPublicHooksTestOnboardingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pandadoc': {
      id: '/api/public/hooks/pandadoc'
      path: '/api/public/hooks/pandadoc'
      fullPath: '/api/public/hooks/pandadoc'
      preLoaderRoute: typeof ApiPublicHooksPandadocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/onboarding-reminders': {
      id: '/api/public/hooks/onboarding-reminders'
      path: '/api/public/hooks/onboarding-reminders'
      fullPath: '/api/public/hooks/onboarding-reminders'
      preLoaderRoute: typeof ApiPublicHooksOnboardingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-contracts': {
      id: '/api/public/hooks/backfill-contracts'
      path: '/api/public/hooks/backfill-contracts'
      fullPath: '/api/public/hooks/backfill-contracts'
      preLoaderRoute: typeof ApiPublicHooksBackfillContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/trophi/$userId': {
      id: '/_authenticated/users/trophi/$userId'
      path: '/$userId'
      fullPath: '/users/trophi/$userId'
      preLoaderRoute: typeof AuthenticatedUsersTrophiUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersTrophiRoute
    }
  }
}

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingBusinessIdRoute: typeof AuthenticatedOnboardingBusinessIdRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingBusinessIdRoute:
      AuthenticatedOnboardingBusinessIdRoute,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedUsersTrophiRouteChildren {
  AuthenticatedUsersTrophiUserIdRoute: typeof AuthenticatedUsersTrophiUserIdRoute
  AuthenticatedUsersTrophiIndexRoute: typeof AuthenticatedUsersTrophiIndexRoute
}

const AuthenticatedUsersTrophiRouteChildren: AuthenticatedUsersTrophiRouteChildren =
  {
    AuthenticatedUsersTrophiUserIdRoute: AuthenticatedUsersTrophiUserIdRoute,
    AuthenticatedUsersTrophiIndexRoute: AuthenticatedUsersTrophiIndexRoute,
  }

const AuthenticatedUsersTrophiRouteWithChildren =
  AuthenticatedUsersTrophiRoute._addFileChildren(
    AuthenticatedUsersTrophiRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersClientUsersRoute: typeof AuthenticatedUsersClientUsersRoute
  AuthenticatedUsersTrophiRoute: typeof AuthenticatedUsersTrophiRouteWithChildren
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersClientUsersRoute: AuthenticatedUsersClientUsersRoute,
  AuthenticatedUsersTrophiRoute: AuthenticatedUsersTrophiRouteWithChildren,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientPortalRoute: typeof AuthenticatedClientPortalRoute
  AuthenticatedLeaderboardsRoute: typeof AuthenticatedLeaderboardsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedCrmBusinessIdRoute: typeof AuthenticatedCrmBusinessIdRoute
  AuthenticatedSettingsPandadocTemplatesRoute: typeof AuthenticatedSettingsPandadocTemplatesRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
  AuthenticatedClientPortalRoute: AuthenticatedClientPortalRoute,
  AuthenticatedLeaderboardsRoute: AuthenticatedLeaderboardsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedCrmBusinessIdRoute: AuthenticatedCrmBusinessIdRoute,
  AuthenticatedSettingsPandadocTemplatesRoute:
    AuthenticatedSettingsPandadocTemplatesRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  ApiPublicHooksBackfillContractsRoute: ApiPublicHooksBackfillContractsRoute,
  ApiPublicHooksOnboardingRemindersRoute:
    ApiPublicHooksOnboardingRemindersRoute,
  ApiPublicHooksPandadocRoute: ApiPublicHooksPandadocRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
  ApiPublicHooksTestOnboardingEmailRoute:
    ApiPublicHooksTestOnboardingEmailRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
